config/routes.rb
Rails.application.routes.draw do
 
  resources :images do
  	resources :comments
  end

  devise_for :users
  resources :users
  
  root 'images#index'
  get "/profile" => "static_pages#profile"
  get "/profile/images" => "static_pages#images"
  get "/profile/comments" => "static_pages#comments"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :private_route

  include UsersHelper

  def profile
    @display_name = display_name(@user)
  end

  def images
    @images = @user.images
  end

  def comments
    @comments = @user.comments
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/comments.html.erb
<p>here are all my comments</p>

<div>
  <% @comments.each do |c|%>
    <%= render partial: "comments/one_comment", locals: {image: c.image, comment: c}%>
  <% end %>
</div> 

app/views/static_pages/images.html.erb
<p>here are all my images</p>

<% @images.each do |image| %>
  <%= render partial: "images/one_image", locals: {image: image}%>
<% end %> 

app/views/static_pages/profile.html.erb
<p>My profile</p>
<p>my user Id:  <%= @user.id%></p>
<p>my first name:  <%= @user.first_name%></p>
<p>my last name:  <%= @user.last_name%></p>
<p>my username:  <%= @user.username%></p>
<p>my email:  <%= @user.email%></p>

// <%= link_to `<button type="button" class="btn btn-primary btn-lg">Large button</button>`, edit_user_path(@user)%>

<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'See all my images', profile_images_path %>  
<%= link_to 'See all comments I wrote', profile_comments_path %> 