config/routes.rb
Rails.application.routes.draw do
 
  resources :images do
  	resources :comments
  end

  devise_for :users
  resources :users
  
  root 'images#index'
  get "/profile" => "static_pages#profile"
  get "/profile/images" => "static_pages#images"
  get "/profile/comments" => "static_pages#comments"

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
    belongs_to :image
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :private_route
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_image
  before_action :can_change_or_delete, only: [:edit, :update, :destroy]

  include CommentsHelper


  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create

    @comment = Comment.new(comment_params.merge(image: @image).merge(user: @user))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to image_path(@image), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to image_path(@image) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params.merge(image: @image).merge(user: @user))
        format.html { redirect_to image_path(@image), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { redirect_to image_path(@image) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to image_path(@image), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private


    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_image
      @image = Image.find(params[:image_id])
    end

    def comment_params
      return params.require(:comment).permit(:content)
    end

    def can_change_or_delete
      unless current_user == @comment.user
        flash[:notice] = "You're not allowed for this action."
        redirect_to image_path(@image)
      end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def current_user_can_change_and_delete_comment(comment)
    current_user == comment.user
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: [@image, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content%>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<%= render 'comments/form' %>

app/views/comments/_one_comment.html.erb
<div>
  <% if comment.user == current_user %>
    <% user = "I"%>
  <% else %>
    <% user = comment.user.first_name%>
  <% end %>
  <p><strong><%= user %></strong> said on <strong><%= comment.created_at.to_date%></strong></p>
  <p><%= comment.content%></p>

  <% if current_user == comment.user%>
    <%= link_to '<button type="button" class="btn btn-success btn-sm">Edit</button>'.html_safe, edit_image_comment_path(image, comment) %> 
    <%= link_to '<button type="button" class="btn btn-danger btn-sm">Delete</button>'.html_safe, image_comment_path(image, comment), method: "delete" %> 
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>