config/routes.rb
Rails.application.routes.draw do
 
  resources :images do
  	resources :comments
  end

  devise_for :users
  resources :users
  
  root 'images#index'
  get "/profile" => "static_pages#profile"
  get "/profile/images" => "static_pages#images"
  get "/profile/comments" => "static_pages#comments"

end

app/models/image.rb
class Image < ApplicationRecord

	belongs_to :author, class_name: 'User'
	has_many :comments
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]
  before_action :private_route, except: [:index]
  before_action :define_current_user, except: [:index]
  before_action :can_change_or_delete, only: [:edit, :update, :destroy]

  include ImagesHelper
  include CommentsHelper

  def index
    @images = Image.all
  end

  def show
    @current_user_can_see_image = current_user_can_see_image(@image)
    @comment = Comment.new
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    permit_image_params
    @image = Image.new(
      author: @user,
      description: @description,
      stream: Base64.strict_encode64(File.open(@image_stream.tempfile).read),
      extension: @extension,
      is_private: @is_private
    )

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    permit_image_params
    respond_to do |format|
      if @image.update(
      author: @user,
      description: @description,
      stream: Base64.strict_encode64(File.open(@image_stream.tempfile).read),
      extension: @extension,
      is_private: @is_private
      )
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_image
      @image = Image.find(params[:id])
    end

    def define_current_user
      @user = current_user
    end

    def permit_image_params
      @image_stream = params.require(:image).permit(:stream)[:stream]
      @extension = @image_stream.original_filename.split(".")[-1]
      @description = params.require(:image).permit(:description)[:description]
      @is_private = params.require(:image).permit(:is_private)[:is_private]
    end

    def can_change_or_delete
      unless current_user == @image.author
        flash[:notice] = "You're not allowed for this action."
        redirect_to image_path(@image)
      end
    end
end

app/helpers/images_helper.rb
module ImagesHelper
  def current_user_can_see_image(image)
    if !image.is_private
      return true
    elsif image.author == current_user
      return true
    else
      return false
    end
  end
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stream %>
    <%= form.file_field :stream %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field checkbox_field">
    <%= form.label :is_private, "make this private" %>
    <%= form.check_box :is_private, checked_value: true, unchecked_value: false %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_one_image.html.erb
<div class="single_image col-lg-2">
  <div class="card">
    <!-- if public image or private image but also current_user = image.author THEN --> 

    <% if !image.is_private || (image.is_private && current_user == image.author) %>
      <%= image_tag "data:image/#{image.extension};base64,#{image.stream}"%>
      
      <% if current_user %>

        <p><strong>Description:</strong><%= image.description %></p>
        <p><strong>Uploaded by:</strong><%= image.author.username %></p>
        <br/>

          <!-- Change or delete only if current_user = image.author --> 

          <% if current_user == image.author %>
          <div class="row justify-content-center">
          <%= link_to '<button type="button" class="btn btn-success btn-sm">Change</button>'.html_safe, edit_image_path(image) %> 
          <%= link_to '<button type="button" class="btn btn-danger btn-sm">Delete</button>'.html_safe, image_path(image), method: "delete" %>
          </div>
        <% end %>


        <!-- lists comments --> 

          <div class="card-body">
            <% image.comments.each do |x|%>
              <%= render partial: "comments/one_comment", locals: {image: image, comment: x}%>
            <% end %>
          </div>

        <%= link_to '<button type="button" class="btn btn-primary btn-block">See</button>'.html_safe, image_path(image) %> 
      <% end %>

      <!-- if private image, only current-user can see this --> 

      <% if image.is_private%>
          <p>Only you, can see this image</p>
      <% end %>
    <% end %>

    <!-- if private image, only current-user can see this (part2) --> 

    <% if image.is_private && current_user != image.author %>
      <h2>Sorry this content is private for you !</h2>
    <% end %>
  </div>
</div>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h3>Gallery</h3>

<%= link_to '<button type="button" class="btn btn-primary btn-sm">New Image</button>'.html_safe, new_image_path %>

<div class="row">
<% @images.each do |image| %>
      <%= render partial: "one_image", locals: {image: image}%>
<% end %>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<% if @current_user_can_see_image %>
  <%= render partial: "one_image", locals: {image: @image}%>
  <%= render partial: "comments/new" %>
<% else %>
  <p>This image is private !</p>
<% end %>

<%= link_to 'Back to Gallery', images_path %>